### ISSUE TITLE
[RFC] WebIO

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#1]
@MikeInnes and I discussed the possibility of a small "hub" package at JuliaCon which would allow package developers to "display something and update it" - something that would work on all web interfaces to Julia (IJulia, Atom, Blink, Escher). This way package authors won't have to worry about setting up fragile `@require IJulia` and `@require Blink` blocks for each interfacre. Or buy into the bureaucracy of wrapping JS libraries in something like Escher (and then have it not work in anything else). WebIO is my take on this hub package.

The idea is to on the one end have IJulia, Atom, Blink and Escher depend on this package and implement the [Provider](https://github.com/shashi/WebDisplay.jl#providers) interface. On the other end Graphics packages like PlotlyJS, Vega, Compose, (even Escher) could use the `Node` and `Context` API to make interactive gizmos.

**Comment by shashi** [comment]
Updated README a bit more, Pinging @stevengj, @MikeInnes, @randyzwitch, @spencerlyon2, @tlnagy

Would really appreciate it if you guys can go through the README and see if this works for you.

**Comment by randyzwitch** [comment]
I think it's a great idea to have a common display interface! I would do a ton more wrapping JS libraries if I knew how to get them to display properly. :)

The only comment I have so far is that I think any packages referenced should be firm dependencies in REQUIRE, not just imported. The conditional imports (especially with whatever is going on with `ComposeDiff`) is the most frustrating part of Escher for me right now. So `FunctionalCollections` should be part of REQUIRES for `WebDisplay`, instead of me adding `FunctionalCollections` to Vega.

https://github.com/shashi/WebDisplay.jl/blob/master/src/WebDisplay.jl#L3

**Comment by shashi** [comment]
@randyzwitch I hadn't added that to REQUIRE. Done now. :)

**Comment by randyzwitch** [comment]
Looks like Conda and JSON also, and maybe IJulia.

**Comment by shashi** [comment]
@randyzwitch Added JSON. The plan is to move the IJulia dependency code into IJulia itself and have IJulia depend on WebDisplay.

**Comment by randyzwitch** [comment]
Is this still going to become a real thing @shashi? With Vega (the JS library) moving to version 3.0, I probably need to re-write Vega.jl anyway, so it'd be great to have this functionality (and for Blink/Atom/Escher) to start my development on.

**Comment by shashi** [comment]
Yes. There are problems with dependency loading and ordering of events has been bugging me. I have sort of a rewrite of the Context business coming up. I'm traveling this week, I hope to put something out by the end of next week!
