### ISSUE TITLE
Simpler default behavior for webio_serve

### ISSUE THREAD

**Issue by waldyrious** [JuliaGizmos/WebIO.jl#189]
As discussed in [this discourse thread](https://discourse.julialang.org/t/some-interact-updates-create-your-custom-widgets-easily-and-composably/14192/), it would be quite convenient if 

    WebIO.webio_serve(req -> ui)

automatically worked as if it was invoked with

    WebIO.webio_serve(page("/", req -> ui))

That is, `webio_serve` could default to serve at the root, if no route is provided explicitly.

I'm not sure if this is technically feasible or even sound in terms of conveying the correct mental model to the user, but at the prompting of @piever I am opening this issue so the possibility can be discussed.

**Comment by piever** [comment]
If everybody is happy with this I can make a PR. I think the easiest fix is to check whether the function has a two argument method and otherwise convert to `page("/", f)`.

**Comment by rdeits** [comment]
Oh, I didn't realize that `page` doesn't actually return a type. That's really awkward. I don't think dispatch based on existence of a two-argument method is a good idea. It's the sort of thing that will *often* work, but will also occasionally break user code it hard to track ways. I think that's a bad tradeoff to make as a library designer. 

In particular, if someone did: 

```
function handle(req)
  <whatever>
end

webio_serve(handle)
```

Then if any other package happened to extend that `handle` method with another argument, even an argument of some brand new type, then the original code will break or start doing the wrong thing. 

I guess instead we could do a couple of things:

1. Just make a new function that takes `(handler, route="/")` and then internally calls `webio_serve(page(route, handler))`
2. Change `webio_serve`'s signature to `webio_serve(handler, route="/")` and have it internally serve `page(route, handler)`. Any users of the old signature would essentially be doing `webio_serve(page("/", page("/", handler)))`, which I think would duplicate the route check but might otherwise work.

**Comment by piever** [comment]
Would multipage apps like:

```julia
webio_serve(Mux.stack(page("/", app1), page("/demo", app2)))
```

still work?

**Comment by rdeits** [comment]
ah, nope. That rules out option 2.

**Comment by piever** [comment]
Maybe we could have a `webio_serve(f::Function)` as it is now and a simpler `webio_serve(ui) = webio_serve(page("/", req -> ui))`? I'm not completely sure, maybe we need two different names.

**Comment by shashi** [comment]
Two names does seem like the way to go.

It's also a good time to move this whole functionality into Mux and have `Mux.serve` do the right thing :-)

**Comment by travigd** [comment]
I've opened an issue on Mux. We should move the integration there and remove this API from WebIO itself.

https://github.com/JuliaWeb/Mux.jl/issues/95
