### ISSUE TITLE
rerendering widget ignores value

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/WebIO.jl#249]
Not sure what is going on here: if I update a slider (or any other widgets), the slider updates correctly but when I rerender it it appears with the old value:

![Screenshot from 2019-03-24 11-10-14](https://user-images.githubusercontent.com/6333339/54878573-93636800-4e26-11e9-9251-8060365d751d.png)

Using the webio-retool branch runs into the same issue.

**Comment by shashi** [comment]
try
```julia
val = Observable(50)
s = slider(1:100, value=val)
s[] = 12
s
```
```julia
s # again
```

**Comment by piever** [comment]
That seems to have the same issue:

![Screenshot from 2019-03-25 11-16-56](https://user-images.githubusercontent.com/6333339/54915652-8f4f4d00-4eef-11e9-8af7-60d7d024a2b9.png)

**Comment by travigd** [comment]
I think this is an issue with Knockout.jl.

https://github.com/JuliaGizmos/Knockout.jl/blob/db75986323428e7a07bd823c92b0d3d1ea57afc9/src/Knockout.jl#L72

The value of index is essentially frozen when the widget is created.

**Comment by shashi** [comment]
Good catch!

**Comment by piever** [comment]
Ah, maybe I get it.... So the issue is that `onimport` is called again when I rerender the widget but in the `onimport` javascript function I'm hard-coding the initial value as a JSON string, instead `onimport` should pick the value from the WebIO scope.

**Comment by travigd** [comment]
Yep; that's not the whole story, since the current values of the observables are embedded in the WebIO payload when the relevant thing is `render`'d; so, for example, a refresh will not show the latest values of the observables.

The solution to that part would be to have observables start as empty and have the client side request the latest values upon being displayed in the frontend. The downside to **that** is that if a notebook is opened and the kernel is gone, there would be no stored values. The solution to **that** would be to have data saved in some kind of local storage (but specifically not `localStorage`, the browser thing). For example, in Jupyter, we can store stuff in notebook metadata (I believe this is what IPyWidgets does); for Blink and Mux, it doesn't really matter (when the kernel is gone, so is the Blink window), so we could set up the save to just be ignored.

**Comment by piever** [comment]
Agh! I'd welcome a PR to Knockout.jl for that, so far I've just changed Knockout to get the value from the scope (the full solution is probably above my paygrade...).

**Comment by travigd** [comment]
I'll try to get one in. :100: 

Gonna close this so we can talk about #258 and since the actual issue exists outside of WebIO itself. Also, can someone who has access to Knockout.jl give me privileges?

**Comment by piever** [comment]
Thanks a lot! I've invited you to join JuliaGizmos so you have access to the various repositories.
