### ISSUE TITLE
"Warning: Please upgrade Blink" when Blink already at newest release

### ISSUE THREAD

**Issue by yha** [JuliaGizmos/WebIO.jl#318]
## The bug
```
julia> using Blink
┌ Warning: Please upgrade Blink for a smoother integration with WebIO.
│   caller = ip:0x0
└ @ Core :-1
```
Blink is already at its newest version (0.10.1)

## Context
Versions:
WebIO v0.8.6
Blink v0.10.1

**Comment by gurvesh** [comment]
I have the same error, and can't use plotlyjs

**Comment by travigd** [comment]
This should be resolved. Please re-open or comment if you're still having issues after upgrading to latest versions of WebIO and Blink.

**Comment by kobussch** [comment]
This is still not fixed on my PC. My setup is 
    - `Windows 10 Home`
    - `Julia 1.3.0-rc4`
    - `WebIO V0.8.11`
    - `Blink V0.12.0`
    - `PlotlyJS  V0.13.0`
Tried everything: update, build, deleted Blink from packages folder, etc. I updated and rebuilt all of the packages in the list above. I even made Blink a development package and changed the version number in AtomShell/install.jl  to the latest (4.0.4), because that is quite outdated. No joy. Problem still exactly as first reported in this thread. Any new suggestions?

**Comment by kobussch** [comment]
Update on my previous comment: after reverting back to the standard package (from the dev package) and re-building Blink, the problem went away. I can only think that the Julia registry system somehow got confused and eventually pulled the right update.

**Comment by baggepinnen** [comment]
It can be hard to get the latest version of blink since did not have the compathelper action installed until recently. I found out that this missing entry was keeping my version of blink low https://github.com/JuliaGizmos/Blink.jl/pull/251
