### ISSUE TITLE
unify `send_request` and `send_command`

### ISSUE THREAD

**Issue by shashi** [JuliaGizmos/WebIO.jl#370]
I want to use `evaljs` in a fire and forget kind of way. I'm trying to send 1000s of these in a for loop, it works blazing fast if I just remove the code that sets up the future and the waiting tasks but of course prints a ton of "Warning: response received for unknonwn....".

Ideally, `send_command` would just be something like `send_request(blah...; async=true)` and `evaljs` can take `async` as an argument which it forwards to `send_request`.

Cheers

**Comment by travigd** [comment]
Closed in favor of #371/#372.

tl;dr:
* `command` is fire-and-forget
* `request` sets up the tasks and futures
* Individual functions can choose the appropriate message type.
* `evaljs` has can be called with `result=true` to use a request, but the default is to use a command (especially since this is the "safer" option)
