### ISSUE TITLE
Release roadmap/plan

### ISSUE THREAD

**Issue by sglyon** [JuliaGizmos/WebIO.jl#42]
I feel a little strange initiating this conversation as an "outsider", but I was hoping to start a discussion about what needs to happen before WebIO can be released on metadata.

Perhaps once a concrete list is laid out, people can contribute to making it happen?

**Comment by shashi** [comment]
Thanks for starting this. I think with #44 in, we can tag a release and promise minimal API breakage in the next release.

I think one little self-contained project that could definitely come from someone other than the usual suspects is #9 -- I wouldn't say this blocks a release, but it's the only feature that is different between IJulia and other back-ends, so that would be pretty awesome to have.

**Comment by shashi** [comment]
Done!
